analytics.onpremise.enable=false
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 1985211,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 1965823,\\n  \\"organizationId\\"\: 2017730,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 1965823\\n}"
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=false
analytics.testcloud.hub.switchHub.enable=false
